
indecopi_usuario:
    resource: "@IndecopiUsuarioBundle/Controller/"
    type:     annotation
    prefix:   /

#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation

indecopi:
    resource: "@indecopiBundle/Resources/config/routing.yml"
    prefix:   /control

#app:
  #  resource: "@AppBundle/Resources/config/routing.yml"
  #  prefix:   /

#app:
 
 #   resource: '@AppBundle/Controller/'
 #   type: annotation


