
indecopi_usuario:
    resource: "@IndecopiUsuarioBundle/Controller/"
    type:     annotation
    prefix:   /

indecopi:
    resource: "@indecopiBundle/Resources/config/routing.yml"
    prefix:   /control


